### ISSUE TITLE
Export the dates from Fristenkalender into an .ical file (Actually 3 PRs)

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/fristenkalender_generator#6]
ical is a file format for calendars. It would be nice to download such a file and have all dates of the Fristenkalender in your own calendar.

Edit Konstantin; Structured Todos:
- [x] Add `icalendar` to the dependencies (requirements.in/txt...) as you did in #2
- [x] Create a PR that just adds the icalendar dependency and nothing else #16 
- [x] create a function that takes a mail adress as input and a "Fristentag" (see #3) as input and returns an Event: `def create_ical(frist:TheClassFromIssue3, attendee:str)->Event`
- [x] write a unittest for the function
- [x] Create a PR for `create_ical` (or a better name) and its test and nothing else
- [x] create a function that exports the created event as file
- [x] unittest for the export using the tmpdir_factory from pytest
- [x] create PR just for the export and its test and nothing else

Here a small code snippet how to create a .ical file

```python
from icalendar import Calendar, Event, vCalAddress, vText
import pytz
from datetime import datetime
import os
from pathlib import Path

cal = Calendar()
cal.add('attendee', 'MAILTO:abc@example.com')
cal.add('attendee', 'MAILTO:xyz@example.com')

event = Event()
event.add('summary', 'Python meeting about calendaring')
event.add('dtstart', datetime(2022, 10, 24, 8, 0, 0, tzinfo=pytz.utc))
event.add('dtend', datetime(2022, 10, 24, 10, 0, 0, tzinfo=pytz.utc))
event.add('dtstamp', datetime(2022, 10, 24, 0, 10, 0, tzinfo=pytz.utc))

organizer = vCalAddress('MAILTO:hello@example.com')
organizer.params['cn'] = vText('Sir Jon')
organizer.params['role'] = vText('CEO')
event['organizer'] = organizer
event['location'] = vText('London, UK')

# Adding events to calendar
cal.add_component(event)

directory = str(Path(__file__).parent.parent)
print("ics file will be generated at ", directory)
with open(os.path.join(directory, 'example.ics'), 'wb') as f:
	f.write(cal.to_ical())
```
