### ISSUE TITLE
Die digitalen Kalendereinträge zu den 𝗪erkt𝗧agen sollten markiert sein, wenn sie nicht im Referenzmonat liegen

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/fristenkalender_generator#76]
### Beispiel
Beispiel 2024: Der 21WT des März 2024 ist der 03. April.

## Anforderung:

Es sollte im digitalen Kalender ersichtlicht sein, dass sich dieser 21WT auf auf einen anderen Monat bezieht.
"Früher", in der analog Version wurde das mit einem Stern ⭐ gelöst.

Der Kontext: Annika Metze designt seit Jahren den analogen Fristenkalender von Hochfrequenz. Ich habe ihr jetzt (mit den Daten aus #66) eine .ics-Datei für ganz 2024 generiert, die sie in ihrem Kalender (son Mac-Dings) öffnet. Sie würde gerne die Einträge von WT, die außerhalb ihres Referenzmonats liegen gekennzeichnet haben.

Bitte wendet euch an Annika Metze, wenn ihr weitere Fragen habt.

## Vorgehen bei der Entwicklung:
- [x] Führt bei der Klasse `FristWithAttributes` eine neue Property/ein neues Field/Attribute ein, z.b. `reference_not_in_same_month: bool`; Das wäre dann z.b. für den 21WT/03. April 2024 `True` aber für den 21WT/29. Februar 2024 `False`  => #80 
- [x] Bitte schaut euch den Fristenkalender 2023 an und ändert die Testdaten entsprechend. https://github.com/Hochfrequenz/fristenkalender_generator => #80 /blob/793894a12c429c3127e2648f912730951cc098bc/unittests/full_years.py#L5
- [x] Geht dann testdriven vor und baut den Code so um, dass es funktioniert. => #80 
- [x] Anschließend ändert bitte die Bezeichnung des Events im .ics (z.b. indem ihr einen Stern dranhängt falls das neue attribute True ist) => #81
